server: 
    port: 8181 
spring:
    application:
        name: api-hyperledger-fabric-spring
fabric:
    channel-name: "mychannel"
    chaincode-name: "basic"
    mspId: "Org1MSP"
    peer-endpoint: "localhost:7051"
    override-auth: "peer0.org1.example.com"
